// Mario

import {
    GEO_ASM, GEO_ROTATION_NODE, GEO_OPEN_NODE, GEO_SWITCH_CASE, GEO_DISPLAY_LIST, GEO_CLOSE_NODE,
    GEO_TRANSLATE_ROTATE, GEO_RETURN, GEO_ANIMATED_PART, GEO_SCALE, GEO_HELD_OBJECT, GEO_BRANCH,
    GEO_NODE_START, GEO_RENDER_RANGE, GEO_SHADOW, GEO_END,
    LAYER_OPAQUE, LAYER_ALPHA, LAYER_TRANSPARENT
} from "../../engine/GeoLayout"

import {
    mario_butt,  mario_cap_off_eyes_closed,  mario_cap_off_eyes_dead,  mario_cap_off_eyes_down, 
    mario_cap_off_eyes_front,  mario_cap_off_eyes_half_closed,  mario_cap_off_eyes_left, 
    mario_cap_off_eyes_right,  mario_cap_off_eyes_up,  mario_cap_on_eyes_closed, 
    mario_cap_on_eyes_dead,  mario_cap_on_eyes_down,  mario_cap_on_eyes_front, 
    mario_cap_on_eyes_half_closed,  mario_cap_on_eyes_left,  mario_cap_on_eyes_right, 
    mario_cap_on_eyes_up,  mario_cap_wings,  mario_cap_wings_transparent,  mario_cap_wings_unused, 
    mario_left_arm,  mario_left_foot,  mario_left_hand_closed,  mario_left_hand_open, 
    mario_left_thigh,  mario_low_poly_butt,  mario_low_poly_cap_off_eyes_closed, 
    mario_low_poly_cap_off_eyes_dead,  mario_low_poly_cap_off_eyes_down, 
    mario_low_poly_cap_off_eyes_front,  mario_low_poly_cap_off_eyes_half_closed, 
    mario_low_poly_cap_off_eyes_left,  mario_low_poly_cap_off_eyes_right, 
    mario_low_poly_cap_off_eyes_up,  mario_low_poly_cap_on_eyes_closed, 
    mario_low_poly_cap_on_eyes_dead,  mario_low_poly_cap_on_eyes_down, 
    mario_low_poly_cap_on_eyes_front,  mario_low_poly_cap_on_eyes_half_closed, 
    mario_low_poly_cap_on_eyes_left,  mario_low_poly_cap_on_eyes_right, 
    mario_low_poly_cap_on_eyes_up,  mario_low_poly_left_arm,  mario_low_poly_left_foot, 
    mario_low_poly_left_hand_closed,  mario_low_poly_left_thigh,  mario_low_poly_right_arm, 
    mario_low_poly_right_foot,  mario_low_poly_right_hand_closed,  mario_low_poly_right_thigh, 
    mario_low_poly_torso,  mario_medium_poly_butt,  mario_medium_poly_left_arm, 
    mario_medium_poly_left_foot,  mario_medium_poly_left_hand_closed,  mario_medium_poly_left_thigh,
     mario_medium_poly_right_arm,  mario_medium_poly_right_foot, 
    mario_medium_poly_right_hand_closed,  mario_medium_poly_right_thigh,  mario_medium_poly_torso, 
    mario_metal_butt,  mario_metal_cap_wings,  mario_metal_cap_wings_transparent, 
    mario_metal_cap_wings_unused,  mario_metal_left_thigh,  mario_metal_low_poly_butt, 
    mario_metal_low_poly_cap_off,  mario_metal_low_poly_cap_on,  mario_metal_low_poly_left_thigh, 
    mario_metal_low_poly_right_foot,  mario_metal_low_poly_right_hand_closed, 
    mario_metal_low_poly_torso,  mario_metal_medium_poly_butt,  mario_metal_medium_poly_left_thigh, 
    mario_metal_medium_poly_right_foot,  mario_metal_medium_poly_right_hand_closed, 
    mario_metal_medium_poly_torso,  mario_metal_right_foot, 
    mario_metal_right_hand_cap_shared_dl_wings,  mario_metal_right_hand_closed, 
    mario_metal_right_hand_open,  mario_right_arm,  mario_right_foot,  mario_right_hand_cap, 
    mario_right_hand_cap_wings,  mario_right_hand_closed,  mario_right_hand_open, 
    mario_right_hand_peace,  mario_right_thigh,  mario_texture_eyes_closed, 
    mario_texture_eyes_closed_unused1,  mario_texture_eyes_closed_unused2,  mario_texture_eyes_dead,
     mario_texture_eyes_down,  mario_texture_eyes_front,  mario_texture_eyes_half_closed, 
    mario_texture_eyes_left,  mario_texture_eyes_right,  mario_texture_eyes_up, 
    mario_texture_hair_sideburn,  mario_texture_m_logo,  mario_texture_metal, 
    mario_texture_metal_wings_half_1,  mario_texture_metal_wings_half_2,  mario_texture_mustache, 
    mario_texture_wings_half_1,  mario_texture_wings_half_2,  mario_texture_yellow_button, 
    mario_torso, 

    mario_butt_dl,  mario_cap_unused_base_bottom_dl,  mario_cap_unused_base_dl, 
    mario_cap_unused_base_top_dl,  mario_cap_unused_dl,  mario_cap_unused_m_logo_dl, 
    mario_cap_wings_unused_end_dl,  mario_cap_wings_unused_initial_dl,  mario_eyes_cap_off_dl, 
    mario_eyes_cap_on_dl,  mario_face_back_hair_cap_on_dl,  mario_face_cap_dl, 
    mario_face_cap_off_dl,  mario_face_cap_on_dl,  mario_face_hair_cap_off_dl, 
    mario_face_part_cap_off_dl,  mario_face_part_cap_on_dl,  mario_hair_sideburn_cap_off_dl, 
    mario_hair_sideburn_cap_on_dl,  mario_left_arm_shared_dl,  mario_left_foot_shared_dl, 
    mario_left_forearm_shared_dl,  mario_left_hand_closed_shared_dl, 
    mario_left_hand_open_shared_dl,  mario_left_leg_shared_dl,  mario_left_thigh_dl, 
    mario_low_poly_butt_dl,  mario_low_poly_eyes_cap_on_dl, 
    mario_low_poly_face_back_hair_cap_on_dl,  mario_low_poly_face_cap_dl, 
    mario_low_poly_face_cap_off_dl,  mario_low_poly_face_cap_on_dl, 
    mario_low_poly_face_hair_cap_off_dl,  mario_low_poly_face_part_cap_off_dl, 
    mario_low_poly_face_part_cap_on_dl,  mario_low_poly_left_arm_shared_dl, 
    mario_low_poly_left_foot_shared_dl,  mario_low_poly_left_forearm_shared_dl, 
    mario_low_poly_left_hand_closed_shared_dl,  mario_low_poly_left_leg_shared_dl, 
    mario_low_poly_left_thigh_dl,  mario_low_poly_mario_eyes_cap_off_dl, 
    mario_low_poly_mario_m_logo_dl,  mario_low_poly_mustache_cap_off_dl, 
    mario_low_poly_mustache_cap_on_dl,  mario_low_poly_pants_overalls_shared_dl, 
    mario_low_poly_right_arm_shared_dl,  mario_low_poly_right_foot_dl, 
    mario_low_poly_right_forearm_shared_dl,  mario_low_poly_right_hand_closed_dl, 
    mario_low_poly_right_leg_shared_dl,  mario_low_poly_right_thigh_shared_dl, 
    mario_low_poly_torso_dl,  mario_low_poly_tshirt_shared_dl,  mario_low_poly_yellow_button_dl, 
    mario_m_logo_dl,  mario_medium_poly_butt_dl,  mario_medium_poly_left_arm_shared_dl, 
    mario_medium_poly_left_foot_shared_dl,  mario_medium_poly_left_forearm_shared_dl, 
    mario_medium_poly_left_hand_closed_shared_dl,  mario_medium_poly_left_leg_shared_dl, 
    mario_medium_poly_left_thigh_dl,  mario_medium_poly_pants_overalls_shared_dl, 
    mario_medium_poly_right_arm_shared_dl,  mario_medium_poly_right_foot_dl, 
    mario_medium_poly_right_forearm_shared_dl,  mario_medium_poly_right_hand_closed_dl, 
    mario_medium_poly_right_leg_shared_dl,  mario_medium_poly_right_thigh_shared_dl, 
    mario_medium_poly_torso_dl,  mario_medium_poly_tshirt_shared_dl, 
    mario_medium_poly_yellow_button_dl,  mario_metal_cap_off_shared_dl, 
    mario_metal_cap_on_shared_dl,  mario_metal_cap_unused_dl,  mario_metal_right_hand_cap_shared_dl,
     mario_metal_torso_shared_dl,  mario_mustache_cap_off_dl,  mario_mustache_cap_on_dl, 
    mario_pants_overalls_shared_dl,  mario_right_arm_shared_dl,  mario_right_foot_dl, 
    mario_right_forearm_shared_dl,  mario_right_hand_cap_bottom_dl,  mario_right_hand_cap_dl, 
    mario_right_hand_cap_hand_position_dl,  mario_right_hand_cap_m_logo_dl, 
    mario_right_hand_cap_top_dl,  mario_right_hand_cap_wings_end_dl, 
    mario_right_hand_cap_wings_half_1_dl,  mario_right_hand_cap_wings_half_2_dl, 
    mario_right_hand_cap_wings_initial_dl,  mario_right_hand_closed_dl,  mario_right_hand_open_dl, 
    mario_right_hand_peace_shared_dl,  mario_right_leg_shared_dl,  mario_right_thigh_shared_dl, 
    mario_torso_dl,  mario_tshirt_shared_dl,  mario_wings_half_1_dl,  mario_wings_half_1_unused_dl, 
    mario_wings_half_2_dl,  mario_wings_half_2_unused_dl,  mario_yellow_button_dl, 
} from "./model.inc"

import { SHADOW_CIRCLE_PLAYER } from "../../game/Shadow"


// Normal Mario Geo

// 0x170002E0
export const mario_geo_face_and_wings = [
    GEO_ASM(0, 'MarioMisc.geo_mario_head_rotation'),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_on_off'),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_eyes'),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_front),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_right), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_left), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_up), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_down), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_on_eyes_dead),
            GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_eyes'),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_front),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_right), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_left), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_up), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_down), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_cap_off_eyes_dead),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_cap_wings), // left
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_cap_wings), // right
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x1700041C
export const mario_geo_left_hand = [
    GEO_SWITCH_CASE(1, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17000494
export const mario_geo_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace), // here we go hand
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// The body loads all the parts with some shared dls to apply the solid color of the dl that has it, the same rule applies to the medium and low poly geos

// 0x1700053C
export const mario_geo_body = [
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_butt), // starts sharing solid color with mario_torso (blue)
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_geo_face_and_wings), // stops sharing because faces has its own dl
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_left_arm), // starts sharing solid color with mario_left_forearm (red)
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_left_hand), // stops sharing because hand has its solid color (white)
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_right_arm), // starts sharing solid color of his dl with mario_right_forearm (red)
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_right_hand), // stops sharing because hand has its solid color (white)
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_left_thigh), // starts sharing solid color of his dl with mario_left_leg (blue)
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_left_foot), // stops sharing because foot has its solid color (brown)
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_right_thigh), // starts sharing solid color of his dl with mario_left_leg (blue)
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_right_foot), // stops sharing because foot has its solid color (brown)
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x170006F8
export const mario_geo_medium_poly_left_hand = [
    GEO_SWITCH_CASE(1, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_medium_poly_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17000770
export const mario_geo_medium_poly_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_medium_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace), // here we go hand
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17000818
export const mario_geo_medium_poly_body = [
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_butt), // starts sharing solid color with mario_torso (blue)
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_medium_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_geo_face_and_wings), // stops sharing because faces has its own dl - medium poly mario uses high poly face
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_left_arm), // starts sharing solid color with mario_left_forearm (red)
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_medium_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_medium_poly_left_hand), // stops sharing because hand has its solid color (white)
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_right_arm), // starts sharing solid color of his dl with mario_right_forearm (red)
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_medium_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_medium_poly_right_hand), // stops sharing because hand has its solid color (white)
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_left_thigh), // starts sharing solid color of his dl with mario_left_leg (blue)
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_medium_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_medium_poly_left_foot), // stops sharing because foot has its solid color (brown)
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_right_thigh), // starts sharing solid color of his dl with mario_left_leg (blue)
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_medium_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_medium_poly_right_foot), // stops sharing because foot has its solid color (brown)
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x170009D4
export const mario_geo_low_poly_face_and_wings = [
    GEO_ASM(0, 'MarioMisc.geo_mario_head_rotation'),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_on_off'),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_eyes'),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_front),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_right), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_left), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_up), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_down), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_on_eyes_dead),
            GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_eyes'),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_front),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_right), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_left), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_up), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_down), // unused
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_cap_off_eyes_dead),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_cap_wings), // left
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_cap_wings), // right
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17000B10
export const mario_geo_low_poly_left_hand = [
    GEO_SWITCH_CASE(1, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17000B88
export const mario_geo_low_poly_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace), // here we go hand
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17000C30
export const mario_geo_low_poly_body = [
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_butt), // starts sharing solid color with mario_torso (blue)
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_low_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_geo_low_poly_face_and_wings), // stops sharing because faces has its own dl
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_left_arm), // starts sharing solid color with mario_left_forearm (red)
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_low_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_low_poly_left_hand), // stops sharing because hand has its solid color (white)
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_right_arm), // starts sharing solid color of his dl with mario_right_forearm (red)
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_low_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_geo_low_poly_right_hand), // stops sharing because hand has its solid color (white)
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_left_thigh), // starts sharing solid color of his dl with mario_left_leg (blue)
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_low_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_low_poly_left_foot), // stops sharing because foot has its solid color (brown)
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_right_thigh), // starts sharing solid color of his dl with mario_left_leg (blue)
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_low_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_right_foot), // stops sharing because foot has its solid color (brown)
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// Vanish Mario Geo

// 0x17000DEC
export const mario_vanish_geo_face_and_wings = [
    GEO_ASM(0, 'MarioMisc.geo_mario_head_rotation'),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_on_off'),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_eyes'),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_front),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_right), // unused
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_left), // unused
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_up), // unused
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_down), // unused
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_on_eyes_dead),
            GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_eyes'),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_front),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_right), // unused
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_left), // unused
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_up), // unused
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_down), // unused
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_off_eyes_dead),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17000F28
export const mario_vanish_geo_left_hand = [
    GEO_SWITCH_CASE(1, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17000FA0
export const mario_vanish_geo_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace), // here we go hand
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// Same rule body as Normal Mario

// 0x17001048
export const mario_vanish_geo_body = [
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_vanish_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_left_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_right_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_left_foot),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_right_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17001204
export const mario_vanish_geo_medium_poly_left_hand = [
    GEO_SWITCH_CASE(1, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_medium_poly_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x1700127C
export const mario_vanish_geo_medium_poly_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_medium_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace), // here we go hand
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17001324
export const mario_vanish_geo_medium_poly_body = [
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_medium_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_vanish_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_left_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_medium_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_medium_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_right_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_medium_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_medium_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_medium_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_medium_poly_left_foot),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_right_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_medium_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_medium_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x170014E0
export const mario_vanish_geo_low_poly_face_and_wings = [
    GEO_ASM(0, 'MarioMisc.geo_mario_head_rotation'),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_on_off'),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_eyes'),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_front),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_right),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_left),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_up),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_down),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_on_eyes_dead),
            GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_eyes'),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_front),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_half_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_closed),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_right),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_left),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_up),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_down),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_cap_off_eyes_dead),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x1700161C
export const mario_vanish_geo_low_poly_left_hand = [
    GEO_SWITCH_CASE(1, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_left_hand_closed),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17001694
export const mario_vanish_geo_low_poly_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace), // here we go hand
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_cap),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_right_hand_cap_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x1700173C
export const mario_vanish_geo_low_poly_body = [
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_low_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_vanish_geo_low_poly_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_left_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_low_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_low_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_right_arm),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_low_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_vanish_geo_low_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_low_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_low_poly_left_foot),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_right_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_low_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// Metal Mario Geo

// 0x170018F8
export const mario_metal_geo_face_and_wings = [
    GEO_ASM(0, 'MarioMisc.geo_mario_head_rotation'),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_on_off'),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_cap_on_shared_dl),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_cap_off_shared_dl),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_cap_wings), // left
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_cap_wings), // right
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x170019A4
export const mario_metal_geo_left_hand = [
    GEO_SWITCH_CASE(1, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17001A1C
export const mario_metal_geo_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace_shared_dl), // here we go hand
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// A difference from Normal Mario is that the dls after the butt and left thigh shares the metal texture of it, same rule applies to the medium and low poly geos

// 0x17001AC4
export const mario_metal_geo_body = [
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_butt), // starts sharing metal texture with the dls below
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_metal_torso_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_geo_face_and_wings), // unlike normal mario geo, these dls still share the metal texture
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_right_hand), // stop sharing because the wing metal cap of it
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_left_thigh), // starts sharing metal texture with the dls below
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17001C80
export const mario_metal_geo_medium_poly_left_hand = [
    GEO_SWITCH_CASE(1, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_medium_poly_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17001CF8
export const mario_metal_geo_medium_poly_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_medium_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace_shared_dl), // here we go hand
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17001DA0
export const mario_metal_geo_medium_poly_body = [
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_medium_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_metal_medium_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_medium_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_medium_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_medium_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_medium_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_medium_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_medium_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_medium_poly_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_medium_poly_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_medium_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_medium_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17001F5C
export const mario_metal_geo_low_poly_face_and_wings = [
    GEO_ASM(0, 'MarioMisc.geo_mario_head_rotation'),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_on_off'),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_low_poly_cap_on),
            GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_low_poly_cap_off),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_cap_wings),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_cap_wings),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17002008
export const mario_metal_geo_low_poly_left_hand = [
    GEO_SWITCH_CASE(1, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_low_poly_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17002080
export const mario_metal_geo_low_poly_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_low_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_right_hand_peace_shared_dl), // here we go hand
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17002128
export const mario_metal_geo_low_poly_body = [
    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_low_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_metal_low_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_geo_low_poly_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_low_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_low_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_low_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_geo_low_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_metal_low_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_low_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_low_poly_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_low_poly_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_low_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_metal_low_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// Metal Vanish Mario Geo

// 0x170022E4
export const mario_metal_vanish_geo_face_and_wings = [
    GEO_ASM(0, 'MarioMisc.geo_mario_head_rotation'),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_on_off'),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_on_shared_dl),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_off_shared_dl),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17002390
export const mario_metal_vanish_geo_left_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17002408
export const mario_metal_vanish_geo_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace_shared_dl), // here we go hand
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// Same rules as Metal Mario

// 0x170024B0
export const mario_metal_vanish_geo_body = [
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_metal_torso_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_vanish_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_vanish_geo_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_vanish_geo_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x1700266C
export const mario_metal_vanish_geo_medium_poly_left_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_medium_poly_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_medium_poly_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x170026E4
export const mario_metal_vanish_geo_medium_poly_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_medium_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace_shared_dl), // here we go hand
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x1700278C
export const mario_metal_vanish_geo_medium_poly_body = [
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_medium_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_metal_medium_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_vanish_geo_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_medium_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_vanish_geo_medium_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_medium_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
                                GEO_OPEN_NODE(),
                                    GEO_BRANCH(1, mario_metal_vanish_geo_medium_poly_right_hand),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_medium_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_medium_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_medium_poly_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_medium_poly_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_medium_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_medium_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17002958
export const mario_metal_vanish_geo_low_poly_face_and_wings = [
    GEO_ASM(0, 'MarioMisc.geo_mario_head_rotation'),
    GEO_ROTATION_NODE(0x00, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_on_off'),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_low_poly_cap_on),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_low_poly_cap_off),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, -126, 22, -40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, -51, 126, -22, 40, -135),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_rotate_wing_cap_wings'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_cap_wings_transparent),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17002A04
export const mario_metal_vanish_geo_low_poly_left_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_low_poly_left_hand_closed_shared_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_left_hand_open_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_low_poly_left_hand_closed_shared_dl),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17002A7C
export const mario_metal_vanish_geo_low_poly_right_hand = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_hand'),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, null),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mario_hand_foot_scaler'),
            GEO_SCALE(0x00, 65536),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_low_poly_right_hand_closed),
            GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_open),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0x00, 0, 0, 0, 'MarioMisc.geo_switch_mario_hand_grab_pos'),
        GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_right_hand_peace_shared_dl), // here we go hand
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_metal_right_hand_cap_shared_dl),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, mario_metal_right_hand_cap_shared_dl_wings),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17002B24
export const mario_metal_vanish_geo_low_poly_body = [
    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, null),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_low_poly_butt),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_move_mario_part_from_parent'),
            GEO_ASM(0, 'MarioMisc.geo_mario_tilt_torso'),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_metal_low_poly_torso),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, null),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, mario_metal_vanish_geo_low_poly_face_and_wings),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_left_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_low_poly_left_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_vanish_geo_low_poly_left_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, null),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_right_arm_shared_dl),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_low_poly_right_forearm_shared_dl),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, mario_metal_vanish_geo_low_poly_right_hand),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_metal_low_poly_left_thigh),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_low_poly_left_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_low_poly_left_foot_shared_dl),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, null),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_low_poly_right_thigh_shared_dl),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_low_poly_right_leg_shared_dl),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, null),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, 'MarioMisc.geo_mario_hand_foot_scaler'),
                            GEO_SCALE(0x00, 65536),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_metal_low_poly_right_foot),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// High Poly

// 0x17002CE0
export const mario_geo_load_body = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_effect'),
    GEO_OPEN_NODE(),
        GEO_BRANCH(1, mario_geo_body),
        GEO_BRANCH(1, mario_vanish_geo_body),
        GEO_BRANCH(1, mario_metal_geo_body),
        GEO_BRANCH(1, mario_metal_vanish_geo_body),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// Medium Poly

// 0x17002D14
export const mario_geo_load_medium_poly_body = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_effect'),
    GEO_OPEN_NODE(),
        GEO_BRANCH(1, mario_geo_medium_poly_body),
        GEO_BRANCH(1, mario_vanish_geo_medium_poly_body),
        GEO_BRANCH(1, mario_metal_geo_medium_poly_body),
        GEO_BRANCH(1, mario_metal_vanish_geo_medium_poly_body),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// Low Poly

// 0x17002D48
export const mario_geo_load_low_poly_body = [
    GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_cap_effect'),
    GEO_OPEN_NODE(),
        GEO_BRANCH(1, mario_geo_low_poly_body),
        GEO_BRANCH(1, mario_vanish_geo_low_poly_body),
        GEO_BRANCH(1, mario_metal_geo_low_poly_body),
        GEO_BRANCH(1, mario_metal_vanish_geo_low_poly_body),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// 0x17002D7C
export const mario_geo_render_body = [
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_RENDER_RANGE(-2048, 600),
        GEO_OPEN_NODE(),
            GEO_BRANCH(1, mario_geo_load_body),
        GEO_CLOSE_NODE(),
        GEO_RENDER_RANGE(600, 1600),
        GEO_OPEN_NODE(),
            GEO_BRANCH(1, mario_geo_load_medium_poly_body),
        GEO_CLOSE_NODE(),
        GEO_RENDER_RANGE(1600, 32767),
        GEO_OPEN_NODE(),
            GEO_BRANCH(1, mario_geo_load_low_poly_body),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_RETURN(),
]

// This last geo is used to load all of Mario Geo in the Level Scripts

// 0x17002DD4
export const mario_geo = [
    GEO_SHADOW(SHADOW_CIRCLE_PLAYER, 0xB4, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0x00, 16384),
        GEO_OPEN_NODE(),
            GEO_ASM(0, 'MarioMisc.geo_mirror_mario_backface_culling'),
            GEO_ASM(0, 'MarioMisc.geo_mirror_mario_set_alpha'),
            GEO_SWITCH_CASE(0, 'MarioMisc.geo_switch_mario_stand_run'),
            GEO_OPEN_NODE(),
                GEO_BRANCH(1, mario_geo_load_body),
                GEO_BRANCH(1, mario_geo_render_body),
            GEO_CLOSE_NODE(),
            GEO_ASM(1, 'MarioMisc.geo_mirror_mario_backface_culling'),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
]

// 1620943063 - 2021-05-13 22:56:56 -0400
