// source: proto/mario.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sm64js.ControllerListMsg', null, global);
goog.exportSymbol('proto.sm64js.ControllerMsg', null, global);
goog.exportSymbol('proto.sm64js.MarioListMsg', null, global);
goog.exportSymbol('proto.sm64js.MarioMsg', null, global);
goog.exportSymbol('proto.sm64js.RootMsg', null, global);
goog.exportSymbol('proto.sm64js.RootMsg.MessageCase', null, global);
goog.exportSymbol('proto.sm64js.Sm64JsMsg', null, global);
goog.exportSymbol('proto.sm64js.Sm64JsMsg.MessageCase', null, global);
goog.exportSymbol('proto.sm64js.ValidPlayersMsg', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sm64js.RootMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.sm64js.RootMsg.oneofGroups_);
};
goog.inherits(proto.sm64js.RootMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sm64js.RootMsg.displayName = 'proto.sm64js.RootMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sm64js.Sm64JsMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.sm64js.Sm64JsMsg.oneofGroups_);
};
goog.inherits(proto.sm64js.Sm64JsMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sm64js.Sm64JsMsg.displayName = 'proto.sm64js.Sm64JsMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sm64js.MarioListMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sm64js.MarioListMsg.repeatedFields_, null);
};
goog.inherits(proto.sm64js.MarioListMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sm64js.MarioListMsg.displayName = 'proto.sm64js.MarioListMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sm64js.ControllerListMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sm64js.ControllerListMsg.repeatedFields_, null);
};
goog.inherits(proto.sm64js.ControllerListMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sm64js.ControllerListMsg.displayName = 'proto.sm64js.ControllerListMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sm64js.MarioMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sm64js.MarioMsg.repeatedFields_, null);
};
goog.inherits(proto.sm64js.MarioMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sm64js.MarioMsg.displayName = 'proto.sm64js.MarioMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sm64js.ControllerMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sm64js.ControllerMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sm64js.ControllerMsg.displayName = 'proto.sm64js.ControllerMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sm64js.ValidPlayersMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sm64js.ValidPlayersMsg.repeatedFields_, null);
};
goog.inherits(proto.sm64js.ValidPlayersMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sm64js.ValidPlayersMsg.displayName = 'proto.sm64js.ValidPlayersMsg';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.sm64js.RootMsg.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.sm64js.RootMsg.MessageCase = {
  MESSAGE_NOT_SET: 0,
  UNCOMPRESSED_SM64JS_MSG: 1,
  COMPRESSED_SM64JS_MSG: 2,
  JSON_BYTES_MSG: 3
};

/**
 * @return {proto.sm64js.RootMsg.MessageCase}
 */
proto.sm64js.RootMsg.prototype.getMessageCase = function() {
  return /** @type {proto.sm64js.RootMsg.MessageCase} */(jspb.Message.computeOneofCase(this, proto.sm64js.RootMsg.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sm64js.RootMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.sm64js.RootMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sm64js.RootMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.RootMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    uncompressedSm64jsMsg: (f = msg.getUncompressedSm64jsMsg()) && proto.sm64js.Sm64JsMsg.toObject(includeInstance, f),
    compressedSm64jsMsg: msg.getCompressedSm64jsMsg_asB64(),
    jsonBytesMsg: msg.getJsonBytesMsg_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sm64js.RootMsg}
 */
proto.sm64js.RootMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sm64js.RootMsg;
  return proto.sm64js.RootMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sm64js.RootMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sm64js.RootMsg}
 */
proto.sm64js.RootMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sm64js.Sm64JsMsg;
      reader.readMessage(value,proto.sm64js.Sm64JsMsg.deserializeBinaryFromReader);
      msg.setUncompressedSm64jsMsg(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setCompressedSm64jsMsg(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setJsonBytesMsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sm64js.RootMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sm64js.RootMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sm64js.RootMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.RootMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUncompressedSm64jsMsg();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sm64js.Sm64JsMsg.serializeBinaryToWriter
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional Sm64JsMsg uncompressed_sm64js_msg = 1;
 * @return {?proto.sm64js.Sm64JsMsg}
 */
proto.sm64js.RootMsg.prototype.getUncompressedSm64jsMsg = function() {
  return /** @type{?proto.sm64js.Sm64JsMsg} */ (
    jspb.Message.getWrapperField(this, proto.sm64js.Sm64JsMsg, 1));
};


/**
 * @param {?proto.sm64js.Sm64JsMsg|undefined} value
 * @return {!proto.sm64js.RootMsg} returns this
*/
proto.sm64js.RootMsg.prototype.setUncompressedSm64jsMsg = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.sm64js.RootMsg.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sm64js.RootMsg} returns this
 */
proto.sm64js.RootMsg.prototype.clearUncompressedSm64jsMsg = function() {
  return this.setUncompressedSm64jsMsg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sm64js.RootMsg.prototype.hasUncompressedSm64jsMsg = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bytes compressed_sm64js_msg = 2;
 * @return {!(string|Uint8Array)}
 */
proto.sm64js.RootMsg.prototype.getCompressedSm64jsMsg = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes compressed_sm64js_msg = 2;
 * This is a type-conversion wrapper around `getCompressedSm64jsMsg()`
 * @return {string}
 */
proto.sm64js.RootMsg.prototype.getCompressedSm64jsMsg_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getCompressedSm64jsMsg()));
};


/**
 * optional bytes compressed_sm64js_msg = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCompressedSm64jsMsg()`
 * @return {!Uint8Array}
 */
proto.sm64js.RootMsg.prototype.getCompressedSm64jsMsg_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getCompressedSm64jsMsg()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.sm64js.RootMsg} returns this
 */
proto.sm64js.RootMsg.prototype.setCompressedSm64jsMsg = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.sm64js.RootMsg.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sm64js.RootMsg} returns this
 */
proto.sm64js.RootMsg.prototype.clearCompressedSm64jsMsg = function() {
  return jspb.Message.setOneofField(this, 2, proto.sm64js.RootMsg.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sm64js.RootMsg.prototype.hasCompressedSm64jsMsg = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bytes json_bytes_msg = 3;
 * @return {!(string|Uint8Array)}
 */
proto.sm64js.RootMsg.prototype.getJsonBytesMsg = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes json_bytes_msg = 3;
 * This is a type-conversion wrapper around `getJsonBytesMsg()`
 * @return {string}
 */
proto.sm64js.RootMsg.prototype.getJsonBytesMsg_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getJsonBytesMsg()));
};


/**
 * optional bytes json_bytes_msg = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getJsonBytesMsg()`
 * @return {!Uint8Array}
 */
proto.sm64js.RootMsg.prototype.getJsonBytesMsg_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getJsonBytesMsg()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.sm64js.RootMsg} returns this
 */
proto.sm64js.RootMsg.prototype.setJsonBytesMsg = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.sm64js.RootMsg.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sm64js.RootMsg} returns this
 */
proto.sm64js.RootMsg.prototype.clearJsonBytesMsg = function() {
  return jspb.Message.setOneofField(this, 3, proto.sm64js.RootMsg.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sm64js.RootMsg.prototype.hasJsonBytesMsg = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.sm64js.Sm64JsMsg.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.sm64js.Sm64JsMsg.MessageCase = {
  MESSAGE_NOT_SET: 0,
  LIST_MSG: 1,
  MARIO_MSG: 2,
  VALID_PLAYERS_MSG: 3
};

/**
 * @return {proto.sm64js.Sm64JsMsg.MessageCase}
 */
proto.sm64js.Sm64JsMsg.prototype.getMessageCase = function() {
  return /** @type {proto.sm64js.Sm64JsMsg.MessageCase} */(jspb.Message.computeOneofCase(this, proto.sm64js.Sm64JsMsg.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sm64js.Sm64JsMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.sm64js.Sm64JsMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sm64js.Sm64JsMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.Sm64JsMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    listMsg: (f = msg.getListMsg()) && proto.sm64js.MarioListMsg.toObject(includeInstance, f),
    marioMsg: (f = msg.getMarioMsg()) && proto.sm64js.MarioMsg.toObject(includeInstance, f),
    validPlayersMsg: (f = msg.getValidPlayersMsg()) && proto.sm64js.ValidPlayersMsg.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sm64js.Sm64JsMsg}
 */
proto.sm64js.Sm64JsMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sm64js.Sm64JsMsg;
  return proto.sm64js.Sm64JsMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sm64js.Sm64JsMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sm64js.Sm64JsMsg}
 */
proto.sm64js.Sm64JsMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sm64js.MarioListMsg;
      reader.readMessage(value,proto.sm64js.MarioListMsg.deserializeBinaryFromReader);
      msg.setListMsg(value);
      break;
    case 2:
      var value = new proto.sm64js.MarioMsg;
      reader.readMessage(value,proto.sm64js.MarioMsg.deserializeBinaryFromReader);
      msg.setMarioMsg(value);
      break;
    case 3:
      var value = new proto.sm64js.ValidPlayersMsg;
      reader.readMessage(value,proto.sm64js.ValidPlayersMsg.deserializeBinaryFromReader);
      msg.setValidPlayersMsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sm64js.Sm64JsMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sm64js.Sm64JsMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sm64js.Sm64JsMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.Sm64JsMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getListMsg();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sm64js.MarioListMsg.serializeBinaryToWriter
    );
  }
  f = message.getMarioMsg();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sm64js.MarioMsg.serializeBinaryToWriter
    );
  }
  f = message.getValidPlayersMsg();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sm64js.ValidPlayersMsg.serializeBinaryToWriter
    );
  }
};


/**
 * optional MarioListMsg list_msg = 1;
 * @return {?proto.sm64js.MarioListMsg}
 */
proto.sm64js.Sm64JsMsg.prototype.getListMsg = function() {
  return /** @type{?proto.sm64js.MarioListMsg} */ (
    jspb.Message.getWrapperField(this, proto.sm64js.MarioListMsg, 1));
};


/**
 * @param {?proto.sm64js.MarioListMsg|undefined} value
 * @return {!proto.sm64js.Sm64JsMsg} returns this
*/
proto.sm64js.Sm64JsMsg.prototype.setListMsg = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.sm64js.Sm64JsMsg.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sm64js.Sm64JsMsg} returns this
 */
proto.sm64js.Sm64JsMsg.prototype.clearListMsg = function() {
  return this.setListMsg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sm64js.Sm64JsMsg.prototype.hasListMsg = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional MarioMsg mario_msg = 2;
 * @return {?proto.sm64js.MarioMsg}
 */
proto.sm64js.Sm64JsMsg.prototype.getMarioMsg = function() {
  return /** @type{?proto.sm64js.MarioMsg} */ (
    jspb.Message.getWrapperField(this, proto.sm64js.MarioMsg, 2));
};


/**
 * @param {?proto.sm64js.MarioMsg|undefined} value
 * @return {!proto.sm64js.Sm64JsMsg} returns this
*/
proto.sm64js.Sm64JsMsg.prototype.setMarioMsg = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.sm64js.Sm64JsMsg.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sm64js.Sm64JsMsg} returns this
 */
proto.sm64js.Sm64JsMsg.prototype.clearMarioMsg = function() {
  return this.setMarioMsg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sm64js.Sm64JsMsg.prototype.hasMarioMsg = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ValidPlayersMsg valid_players_msg = 3;
 * @return {?proto.sm64js.ValidPlayersMsg}
 */
proto.sm64js.Sm64JsMsg.prototype.getValidPlayersMsg = function() {
  return /** @type{?proto.sm64js.ValidPlayersMsg} */ (
    jspb.Message.getWrapperField(this, proto.sm64js.ValidPlayersMsg, 3));
};


/**
 * @param {?proto.sm64js.ValidPlayersMsg|undefined} value
 * @return {!proto.sm64js.Sm64JsMsg} returns this
*/
proto.sm64js.Sm64JsMsg.prototype.setValidPlayersMsg = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.sm64js.Sm64JsMsg.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sm64js.Sm64JsMsg} returns this
 */
proto.sm64js.Sm64JsMsg.prototype.clearValidPlayersMsg = function() {
  return this.setValidPlayersMsg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sm64js.Sm64JsMsg.prototype.hasValidPlayersMsg = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sm64js.MarioListMsg.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sm64js.MarioListMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.sm64js.MarioListMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sm64js.MarioListMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.MarioListMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    marioList: jspb.Message.toObjectList(msg.getMarioList(),
    proto.sm64js.MarioMsg.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sm64js.MarioListMsg}
 */
proto.sm64js.MarioListMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sm64js.MarioListMsg;
  return proto.sm64js.MarioListMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sm64js.MarioListMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sm64js.MarioListMsg}
 */
proto.sm64js.MarioListMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.sm64js.MarioMsg;
      reader.readMessage(value,proto.sm64js.MarioMsg.deserializeBinaryFromReader);
      msg.addMario(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sm64js.MarioListMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sm64js.MarioListMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sm64js.MarioListMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.MarioListMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarioList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.sm64js.MarioMsg.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MarioMsg mario = 2;
 * @return {!Array<!proto.sm64js.MarioMsg>}
 */
proto.sm64js.MarioListMsg.prototype.getMarioList = function() {
  return /** @type{!Array<!proto.sm64js.MarioMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sm64js.MarioMsg, 2));
};


/**
 * @param {!Array<!proto.sm64js.MarioMsg>} value
 * @return {!proto.sm64js.MarioListMsg} returns this
*/
proto.sm64js.MarioListMsg.prototype.setMarioList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.sm64js.MarioMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sm64js.MarioMsg}
 */
proto.sm64js.MarioListMsg.prototype.addMario = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.sm64js.MarioMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sm64js.MarioListMsg} returns this
 */
proto.sm64js.MarioListMsg.prototype.clearMarioList = function() {
  return this.setMarioList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sm64js.ControllerListMsg.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sm64js.ControllerListMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.sm64js.ControllerListMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sm64js.ControllerListMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.ControllerListMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    controllerList: jspb.Message.toObjectList(msg.getControllerList(),
    proto.sm64js.ControllerMsg.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sm64js.ControllerListMsg}
 */
proto.sm64js.ControllerListMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sm64js.ControllerListMsg;
  return proto.sm64js.ControllerListMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sm64js.ControllerListMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sm64js.ControllerListMsg}
 */
proto.sm64js.ControllerListMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sm64js.ControllerMsg;
      reader.readMessage(value,proto.sm64js.ControllerMsg.deserializeBinaryFromReader);
      msg.addController(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sm64js.ControllerListMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sm64js.ControllerListMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sm64js.ControllerListMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.ControllerListMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getControllerList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.sm64js.ControllerMsg.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ControllerMsg controller = 1;
 * @return {!Array<!proto.sm64js.ControllerMsg>}
 */
proto.sm64js.ControllerListMsg.prototype.getControllerList = function() {
  return /** @type{!Array<!proto.sm64js.ControllerMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sm64js.ControllerMsg, 1));
};


/**
 * @param {!Array<!proto.sm64js.ControllerMsg>} value
 * @return {!proto.sm64js.ControllerListMsg} returns this
*/
proto.sm64js.ControllerListMsg.prototype.setControllerList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.sm64js.ControllerMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sm64js.ControllerMsg}
 */
proto.sm64js.ControllerListMsg.prototype.addController = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.sm64js.ControllerMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sm64js.ControllerListMsg} returns this
 */
proto.sm64js.ControllerListMsg.prototype.clearControllerList = function() {
  return this.setControllerList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sm64js.MarioMsg.repeatedFields_ = [13,14,15,16,18];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sm64js.MarioMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.sm64js.MarioMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sm64js.MarioMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.MarioMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    controller: (f = msg.getController()) && proto.sm64js.ControllerMsg.toObject(includeInstance, f),
    playername: jspb.Message.getFieldWithDefault(msg, 2, ""),
    action: jspb.Message.getFieldWithDefault(msg, 3, 0),
    prevaction: jspb.Message.getFieldWithDefault(msg, 4, 0),
    actionstate: jspb.Message.getFieldWithDefault(msg, 5, 0),
    actiontimer: jspb.Message.getFieldWithDefault(msg, 6, 0),
    actionarg: jspb.Message.getFieldWithDefault(msg, 7, 0),
    invinctimer: jspb.Message.getFieldWithDefault(msg, 8, 0),
    framessincea: jspb.Message.getFieldWithDefault(msg, 9, 0),
    framessinceb: jspb.Message.getFieldWithDefault(msg, 10, 0),
    wallkicktimer: jspb.Message.getFieldWithDefault(msg, 11, 0),
    doublejumptimer: jspb.Message.getFieldWithDefault(msg, 12, 0),
    faceangleList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    anglevelList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    posList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 15)) == null ? undefined : f,
    velList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 16)) == null ? undefined : f,
    forwardvel: jspb.Message.getFloatingPointFieldWithDefault(msg, 17, 0.0),
    rawdataList: (f = jspb.Message.getRepeatedField(msg, 18)) == null ? undefined : f,
    usedobjid: jspb.Message.getFieldWithDefault(msg, 19, 0),
    channelid: jspb.Message.getFieldWithDefault(msg, 20, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sm64js.MarioMsg}
 */
proto.sm64js.MarioMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sm64js.MarioMsg;
  return proto.sm64js.MarioMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sm64js.MarioMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sm64js.MarioMsg}
 */
proto.sm64js.MarioMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sm64js.ControllerMsg;
      reader.readMessage(value,proto.sm64js.ControllerMsg.deserializeBinaryFromReader);
      msg.setController(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayername(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAction(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPrevaction(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setActionstate(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setActiontimer(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setActionarg(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setInvinctimer(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFramessincea(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFramessinceb(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWallkicktimer(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDoublejumptimer(value);
      break;
    case 13:
      var value = /** @type {!Array<number>} */ (reader.readPackedSint32());
      msg.setFaceangleList(value);
      break;
    case 14:
      var value = /** @type {!Array<number>} */ (reader.readPackedSint32());
      msg.setAnglevelList(value);
      break;
    case 15:
      var value = /** @type {!Array<number>} */ (reader.readPackedFloat());
      msg.setPosList(value);
      break;
    case 16:
      var value = /** @type {!Array<number>} */ (reader.readPackedFloat());
      msg.setVelList(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setForwardvel(value);
      break;
    case 18:
      var value = /** @type {!Array<number>} */ (reader.readPackedSint32());
      msg.setRawdataList(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUsedobjid(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setChannelid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sm64js.MarioMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sm64js.MarioMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sm64js.MarioMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.MarioMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getController();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sm64js.ControllerMsg.serializeBinaryToWriter
    );
  }
  f = message.getPlayername();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAction();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getPrevaction();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getActionstate();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getActiontimer();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getActionarg();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getInvinctimer();
  if (f !== 0) {
    writer.writeSint32(
      8,
      f
    );
  }
  f = message.getFramessincea();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getFramessinceb();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getWallkicktimer();
  if (f !== 0) {
    writer.writeUint32(
      11,
      f
    );
  }
  f = message.getDoublejumptimer();
  if (f !== 0) {
    writer.writeUint32(
      12,
      f
    );
  }
  f = message.getFaceangleList();
  if (f.length > 0) {
    writer.writePackedSint32(
      13,
      f
    );
  }
  f = message.getAnglevelList();
  if (f.length > 0) {
    writer.writePackedSint32(
      14,
      f
    );
  }
  f = message.getPosList();
  if (f.length > 0) {
    writer.writePackedFloat(
      15,
      f
    );
  }
  f = message.getVelList();
  if (f.length > 0) {
    writer.writePackedFloat(
      16,
      f
    );
  }
  f = message.getForwardvel();
  if (f !== 0.0) {
    writer.writeFloat(
      17,
      f
    );
  }
  f = message.getRawdataList();
  if (f.length > 0) {
    writer.writePackedSint32(
      18,
      f
    );
  }
  f = message.getUsedobjid();
  if (f !== 0) {
    writer.writeUint32(
      19,
      f
    );
  }
  f = message.getChannelid();
  if (f !== 0) {
    writer.writeUint32(
      20,
      f
    );
  }
};


/**
 * optional ControllerMsg controller = 1;
 * @return {?proto.sm64js.ControllerMsg}
 */
proto.sm64js.MarioMsg.prototype.getController = function() {
  return /** @type{?proto.sm64js.ControllerMsg} */ (
    jspb.Message.getWrapperField(this, proto.sm64js.ControllerMsg, 1));
};


/**
 * @param {?proto.sm64js.ControllerMsg|undefined} value
 * @return {!proto.sm64js.MarioMsg} returns this
*/
proto.sm64js.MarioMsg.prototype.setController = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.clearController = function() {
  return this.setController(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sm64js.MarioMsg.prototype.hasController = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string playerName = 2;
 * @return {string}
 */
proto.sm64js.MarioMsg.prototype.getPlayername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setPlayername = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 action = 3;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getAction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setAction = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 prevAction = 4;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getPrevaction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setPrevaction = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 actionState = 5;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getActionstate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setActionstate = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 actionTimer = 6;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getActiontimer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setActiontimer = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 actionArg = 7;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getActionarg = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setActionarg = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional sint32 invincTimer = 8;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getInvinctimer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setInvinctimer = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 framesSinceA = 9;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getFramessincea = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setFramessincea = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint32 framesSinceB = 10;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getFramessinceb = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setFramessinceb = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional uint32 wallKickTimer = 11;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getWallkicktimer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setWallkicktimer = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional uint32 doubleJumpTimer = 12;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getDoublejumptimer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setDoublejumptimer = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * repeated sint32 faceAngle = 13;
 * @return {!Array<number>}
 */
proto.sm64js.MarioMsg.prototype.getFaceangleList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 13));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setFaceangleList = function(value) {
  return jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.addFaceangle = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.clearFaceangleList = function() {
  return this.setFaceangleList([]);
};


/**
 * repeated sint32 angleVel = 14;
 * @return {!Array<number>}
 */
proto.sm64js.MarioMsg.prototype.getAnglevelList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 14));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setAnglevelList = function(value) {
  return jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.addAnglevel = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.clearAnglevelList = function() {
  return this.setAnglevelList([]);
};


/**
 * repeated float pos = 15;
 * @return {!Array<number>}
 */
proto.sm64js.MarioMsg.prototype.getPosList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 15));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setPosList = function(value) {
  return jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.addPos = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.clearPosList = function() {
  return this.setPosList([]);
};


/**
 * repeated float vel = 16;
 * @return {!Array<number>}
 */
proto.sm64js.MarioMsg.prototype.getVelList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 16));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setVelList = function(value) {
  return jspb.Message.setField(this, 16, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.addVel = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 16, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.clearVelList = function() {
  return this.setVelList([]);
};


/**
 * optional float forwardVel = 17;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getForwardvel = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 17, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setForwardvel = function(value) {
  return jspb.Message.setProto3FloatField(this, 17, value);
};


/**
 * repeated sint32 rawData = 18;
 * @return {!Array<number>}
 */
proto.sm64js.MarioMsg.prototype.getRawdataList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 18));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setRawdataList = function(value) {
  return jspb.Message.setField(this, 18, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.addRawdata = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 18, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.clearRawdataList = function() {
  return this.setRawdataList([]);
};


/**
 * optional uint32 usedObjID = 19;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getUsedobjid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setUsedobjid = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional uint32 channelID = 20;
 * @return {number}
 */
proto.sm64js.MarioMsg.prototype.getChannelid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.MarioMsg} returns this
 */
proto.sm64js.MarioMsg.prototype.setChannelid = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sm64js.ControllerMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.sm64js.ControllerMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sm64js.ControllerMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.ControllerMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    stickx: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    sticky: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    stickmag: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    buttondown: jspb.Message.getFieldWithDefault(msg, 4, 0),
    buttonpressed: jspb.Message.getFieldWithDefault(msg, 5, 0),
    camerayaw: jspb.Message.getFieldWithDefault(msg, 6, 0),
    channelid: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sm64js.ControllerMsg}
 */
proto.sm64js.ControllerMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sm64js.ControllerMsg;
  return proto.sm64js.ControllerMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sm64js.ControllerMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sm64js.ControllerMsg}
 */
proto.sm64js.ControllerMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setStickx(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSticky(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setStickmag(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setButtondown(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setButtonpressed(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setCamerayaw(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setChannelid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sm64js.ControllerMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sm64js.ControllerMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sm64js.ControllerMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.ControllerMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStickx();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getSticky();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getStickmag();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getButtondown();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getButtonpressed();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getCamerayaw();
  if (f !== 0) {
    writer.writeSint32(
      6,
      f
    );
  }
  f = message.getChannelid();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
};


/**
 * optional float stickX = 1;
 * @return {number}
 */
proto.sm64js.ControllerMsg.prototype.getStickx = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.ControllerMsg} returns this
 */
proto.sm64js.ControllerMsg.prototype.setStickx = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float stickY = 2;
 * @return {number}
 */
proto.sm64js.ControllerMsg.prototype.getSticky = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.ControllerMsg} returns this
 */
proto.sm64js.ControllerMsg.prototype.setSticky = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float stickMag = 3;
 * @return {number}
 */
proto.sm64js.ControllerMsg.prototype.getStickmag = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.ControllerMsg} returns this
 */
proto.sm64js.ControllerMsg.prototype.setStickmag = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional uint32 buttonDown = 4;
 * @return {number}
 */
proto.sm64js.ControllerMsg.prototype.getButtondown = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.ControllerMsg} returns this
 */
proto.sm64js.ControllerMsg.prototype.setButtondown = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 buttonPressed = 5;
 * @return {number}
 */
proto.sm64js.ControllerMsg.prototype.getButtonpressed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.ControllerMsg} returns this
 */
proto.sm64js.ControllerMsg.prototype.setButtonpressed = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional sint32 cameraYaw = 6;
 * @return {number}
 */
proto.sm64js.ControllerMsg.prototype.getCamerayaw = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.ControllerMsg} returns this
 */
proto.sm64js.ControllerMsg.prototype.setCamerayaw = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 channelID = 7;
 * @return {number}
 */
proto.sm64js.ControllerMsg.prototype.getChannelid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.sm64js.ControllerMsg} returns this
 */
proto.sm64js.ControllerMsg.prototype.setChannelid = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sm64js.ValidPlayersMsg.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sm64js.ValidPlayersMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.sm64js.ValidPlayersMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sm64js.ValidPlayersMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.ValidPlayersMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    validplayersList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sm64js.ValidPlayersMsg}
 */
proto.sm64js.ValidPlayersMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sm64js.ValidPlayersMsg;
  return proto.sm64js.ValidPlayersMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sm64js.ValidPlayersMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sm64js.ValidPlayersMsg}
 */
proto.sm64js.ValidPlayersMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setValidplayersList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sm64js.ValidPlayersMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sm64js.ValidPlayersMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sm64js.ValidPlayersMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sm64js.ValidPlayersMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValidplayersList();
  if (f.length > 0) {
    writer.writePackedUint32(
      1,
      f
    );
  }
};


/**
 * repeated uint32 validPlayers = 1;
 * @return {!Array<number>}
 */
proto.sm64js.ValidPlayersMsg.prototype.getValidplayersList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.sm64js.ValidPlayersMsg} returns this
 */
proto.sm64js.ValidPlayersMsg.prototype.setValidplayersList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.sm64js.ValidPlayersMsg} returns this
 */
proto.sm64js.ValidPlayersMsg.prototype.addValidplayers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sm64js.ValidPlayersMsg} returns this
 */
proto.sm64js.ValidPlayersMsg.prototype.clearValidplayersList = function() {
  return this.setValidplayersList([]);
};


goog.object.extend(exports, proto.sm64js);
