// source: Programming/sm64js/proto/mario.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.MarioListMsg', null, global);
goog.exportSymbol('proto.MarioMsg', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MarioListMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MarioListMsg.repeatedFields_, null);
};
goog.inherits(proto.MarioListMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MarioListMsg.displayName = 'proto.MarioListMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MarioMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MarioMsg.repeatedFields_, null);
};
goog.inherits(proto.MarioMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MarioMsg.displayName = 'proto.MarioMsg';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MarioListMsg.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MarioListMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.MarioListMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MarioListMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MarioListMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    marioList: jspb.Message.toObjectList(msg.getMarioList(),
    proto.MarioMsg.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MarioListMsg}
 */
proto.MarioListMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MarioListMsg;
  return proto.MarioListMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MarioListMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MarioListMsg}
 */
proto.MarioListMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MarioMsg;
      reader.readMessage(value,proto.MarioMsg.deserializeBinaryFromReader);
      msg.addMario(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MarioListMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MarioListMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MarioListMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MarioListMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMarioList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.MarioMsg.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MarioMsg mario = 1;
 * @return {!Array<!proto.MarioMsg>}
 */
proto.MarioListMsg.prototype.getMarioList = function() {
  return /** @type{!Array<!proto.MarioMsg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.MarioMsg, 1));
};


/**
 * @param {!Array<!proto.MarioMsg>} value
 * @return {!proto.MarioListMsg} returns this
*/
proto.MarioListMsg.prototype.setMarioList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.MarioMsg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.MarioMsg}
 */
proto.MarioListMsg.prototype.addMario = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.MarioMsg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MarioListMsg} returns this
 */
proto.MarioListMsg.prototype.clearMarioList = function() {
  return this.setMarioList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MarioMsg.repeatedFields_ = [6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MarioMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.MarioMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MarioMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MarioMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    playername: jspb.Message.getFieldWithDefault(msg, 1, ""),
    skinid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    animid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    animframe: jspb.Message.getFieldWithDefault(msg, 4, 0),
    socketid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    posList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    angleList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MarioMsg}
 */
proto.MarioMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MarioMsg;
  return proto.MarioMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MarioMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MarioMsg}
 */
proto.MarioMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayername(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkinid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAnimid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAnimframe(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSocketid(value);
      break;
    case 6:
      var value = /** @type {!Array<number>} */ (reader.readPackedSint32());
      msg.setPosList(value);
      break;
    case 7:
      var value = /** @type {!Array<number>} */ (reader.readPackedSint32());
      msg.setAngleList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MarioMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MarioMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MarioMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MarioMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSkinid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getAnimid();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getAnimframe();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSocketid();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getPosList();
  if (f.length > 0) {
    writer.writePackedSint32(
      6,
      f
    );
  }
  f = message.getAngleList();
  if (f.length > 0) {
    writer.writePackedSint32(
      7,
      f
    );
  }
};


/**
 * optional string playerName = 1;
 * @return {string}
 */
proto.MarioMsg.prototype.getPlayername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.setPlayername = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 skinID = 2;
 * @return {number}
 */
proto.MarioMsg.prototype.getSkinid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.setSkinid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 animID = 3;
 * @return {number}
 */
proto.MarioMsg.prototype.getAnimid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.setAnimid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 animFrame = 4;
 * @return {number}
 */
proto.MarioMsg.prototype.getAnimframe = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.setAnimframe = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 socketID = 5;
 * @return {number}
 */
proto.MarioMsg.prototype.getSocketid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.setSocketid = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated sint32 pos = 6;
 * @return {!Array<number>}
 */
proto.MarioMsg.prototype.getPosList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.setPosList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.addPos = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.clearPosList = function() {
  return this.setPosList([]);
};


/**
 * repeated sint32 angle = 7;
 * @return {!Array<number>}
 */
proto.MarioMsg.prototype.getAngleList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.setAngleList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.addAngle = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MarioMsg} returns this
 */
proto.MarioMsg.prototype.clearAngleList = function() {
  return this.setAngleList([]);
};


goog.object.extend(exports, proto);
