import * as Macros from "./dynlist_macros"
import { DynlistProcInstance as Dynlist } from "../DynlistProc"

export const dynlist_unused = [  /// actually is used
    Macros.StartList(),
    Macros.StartGroup("spotvg"),
    Macros.MakeVertex(0.0, 0.0, 0.0),
    Macros.MakeVertex(1.0, -1.0, 1.0),
    Macros.SetParamF(1, 0.0),
    Macros.SetParamF(1, 0.0),
    Macros.MakeVertex(1.0, 1.0, 1.0),
    Macros.SetParamF(1, 0.0),
    Macros.MakeVertex(-1.0, 1.0, 1.0),
    Macros.SetParamF(1, 0.0),
    Macros.MakeVertex(-1.0, -1.0, 1.0),
    Macros.SetParamF(1, 0.0),
    Macros.MakeVertex(0.0, 0.0, 0.0),
    Macros.EndGroup("spotvg"),
    Macros.StartGroup("spotpg"),
    Macros.MakeDynObj(Dynlist.D_FACE, null),
    Macros.SetMaterial(null, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 2),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 3),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 5),
    Macros.MakeDynObj(Dynlist.D_FACE, null),
    Macros.SetMaterial(null, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 3),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 4),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 5),
    Macros.MakeDynObj(Dynlist.D_FACE, null),
    Macros.SetMaterial(null, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 4),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 1),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 5),
    Macros.MakeDynObj(Dynlist.D_FACE, null),
    Macros.SetMaterial(null, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 1),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 2),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 5),
    Macros.MakeDynObj(Dynlist.D_FACE, null),
    Macros.SetMaterial(null, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 3),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 2),
    Macros.MakeDynObj(Dynlist.D_FACE, null),
    Macros.SetMaterial(null, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 4),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 3),
    Macros.MakeDynObj(Dynlist.D_FACE, null),
    Macros.SetMaterial(null, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 1),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 4),
    Macros.MakeDynObj(Dynlist.D_FACE, null),
    Macros.SetMaterial(null, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 0),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 2),
    Macros.SetParamPtr(Dynlist.PARM_PTR_OBJ_VTX, 1),
    Macros.EndGroup("spotpg"),
    Macros.UseObj("spotpg"),
    Macros.MapVertices("spotvg"),
    Macros.MakeDynObj(Dynlist.D_SHAPE, "spot_sh"),
    Macros.SetNodeGroup("spotvg"),
    Macros.SetPlaneGroup("spotpg"),
    Macros.SetParamF(1, 0.1),
    Macros.StopList()
]