import { GeoLayoutInstance as Geo } from "../../engine/GeoLayout"
import { bobomb_seg8_dl_08022D08, bobomb_seg8_dl_08023270, bobomb_seg8_dl_08022D78, bobomb_seg8_dl_08023378, bobomb_seg8_dl_08023480, bobomb_seg8_dl_08022B58, bobomb_seg8_dl_08022B88 } from "./model.inc"
import { SHADOW_CIRCLE_4_VERTS } from "../../game/Shadow"
import { geo_switch_anim_state } from "../../game/ObjectHelpers"


export const black_bobomb_geo = [
	{ command: Geo.node_shadow,args: [SHADOW_CIRCLE_4_VERTS, 0xC8, 70],},
	{ command: Geo.open_node },
	{ command: Geo.node_scale,args: [0x00, 24576],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_billboard },
	{ command: Geo.open_node },
	{ command: Geo.display_list, args: [Geo.LAYER_ALPHA, bobomb_seg8_dl_08022D08] },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 57, -60, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 91, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, bobomb_seg8_dl_08023270],},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 55, 62, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 91, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, bobomb_seg8_dl_08023378],},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, bobomb_seg8_dl_08023480],},
	{ command: Geo.node_switch_case,args: [2, geo_switch_anim_state],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_ALPHA, 0, 0, 0, bobomb_seg8_dl_08022B58],},
	{ command: Geo.node_animated_part,args: [Geo.LAYER_ALPHA, 0, 0, 0, bobomb_seg8_dl_08022B88],},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_end },
]

export const bobomb_buddy_geo = [
	{ command: Geo.node_shadow,args: [SHADOW_CIRCLE_4_VERTS, 0xC8, 70],},
	{ command: Geo.open_node },
	{ command: Geo.node_scale,args: [0x00, 24576],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_billboard },
	{ command: Geo.open_node },
	{ command: Geo.display_list, args: [Geo.LAYER_ALPHA, bobomb_seg8_dl_08022D78] },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 57, -60, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 91, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, bobomb_seg8_dl_08023270],},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 55, 62, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 91, 0, 0, null],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, bobomb_seg8_dl_08023378],},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_OPAQUE, 0, 0, 0, bobomb_seg8_dl_08023480],},
	{ command: Geo.node_switch_case,args: [2, geo_switch_anim_state],},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part,args: [Geo.LAYER_ALPHA, 0, 0, 0, bobomb_seg8_dl_08022B58],},
	{ command: Geo.node_animated_part,args: [Geo.LAYER_ALPHA, 0, 0, 0, bobomb_seg8_dl_08022B88],},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_end },
]
