export const MODEL_NONE                            = 0x00

export const MODEL_LEVEL_GEOMETRY_03               = 0x03
export const MODEL_LEVEL_GEOMETRY_04               = 0x04
export const MODEL_LEVEL_GEOMETRY_05               = 0x05
export const MODEL_LEVEL_GEOMETRY_06               = 0x06
export const MODEL_LEVEL_GEOMETRY_07               = 0x07
export const MODEL_LEVEL_GEOMETRY_08               = 0x08
export const MODEL_LEVEL_GEOMETRY_09               = 0x09
export const MODEL_LEVEL_GEOMETRY_0A               = 0x0A
export const MODEL_LEVEL_GEOMETRY_0B               = 0x0B
export const MODEL_LEVEL_GEOMETRY_0C               = 0x0C
export const MODEL_LEVEL_GEOMETRY_0D               = 0x0D
export const MODEL_LEVEL_GEOMETRY_0E               = 0x0E
export const MODEL_LEVEL_GEOMETRY_0F               = 0x0F
export const MODEL_LEVEL_GEOMETRY_10               = 0x10
export const MODEL_LEVEL_GEOMETRY_11               = 0x11
export const MODEL_LEVEL_GEOMETRY_12               = 0x12
export const MODEL_LEVEL_GEOMETRY_13               = 0x13
export const MODEL_LEVEL_GEOMETRY_14               = 0x14
export const MODEL_LEVEL_GEOMETRY_15               = 0x15
export const MODEL_LEVEL_GEOMETRY_16               = 0x16

export const MODEL_BOB_BUBBLY_TREE                 = 0x17        // bubbly_tree_geo
export const MODEL_WDW_BUBBLY_TREE                 = 0x17        // bubbly_tree_geo
export const MODEL_CASTLE_GROUNDS_BUBBLY_TREE      = 0x17        // bubbly_tree_geo
export const MODEL_WF_BUBBLY_TREE                  = 0x17        // bubbly_tree_geo
export const MODEL_THI_BUBBLY_TREE                 = 0x17        // bubbly_tree_geo
export const MODEL_COURTYARD_SPIKY_TREE            = 0x18        // spiky_tree_geo
export const MODEL_CCM_SNOW_TREE                   = 0x19        // snow_tree_geo
export const MODEL_SL_SNOW_TREE                    = 0x19        // snow_tree_geo
export const MODEL_UNKNOWN_TREE_1A                 = 0x1A        // referenced in special presets, undefined
export const MODEL_SSL_PALM_TREE                   = 0x1B        // palm_tree_geo
export const MODEL_CASTLE_CASTLE_DOOR_UNUSED       = 0x1C        // castle_door_geo - unused, original id
export const MODEL_CASTLE_WOODEN_DOOR_UNUSED       = 0x1D        // wooden_door_geo - unused, original id
export const MODEL_BBH_HAUNTED_DOOR                = 0x1D        // haunted_door_geo
export const MODEL_HMC_WOODEN_DOOR                 = 0x1D        // wooden_door_geo
export const MODEL_UNKNOWN_DOOR_1E                 = 0x1E        // referenced in special presets, undefined
export const MODEL_HMC_METAL_DOOR                  = 0x1F        // metal_door_geo
export const MODEL_HMC_HAZY_MAZE_DOOR              = 0x20        // hazy_maze_door_geo
export const MODEL_UNKNOWN_DOOR_21                 = 0x21        // referenced in special presets, undefined
export const MODEL_CASTLE_DOOR_0_STARS             = 0x22        // castle_door_0_star_geo
export const MODEL_CASTLE_DOOR_1_STAR              = 0x23        // castle_door_1_star_geo
export const MODEL_CASTLE_DOOR_3_STARS             = 0x24        // castle_door_3_stars_geo
export const MODEL_CASTLE_KEY_DOOR                 = 0x25        // key_door_geo
export const MODEL_CASTLE_CASTLE_DOOR              = 0x26        // castle_door_geo - used duplicate
export const MODEL_CASTLE_GROUNDS_CASTLE_DOOR      = 0x26        // castle_door_geo - used duplicate
export const MODEL_CASTLE_WOODEN_DOOR              = 0x27        // wooden_door_geo
export const MODEL_COURTYARD_WOODEN_DOOR           = 0x27        // wooden_door_geo
export const MODEL_CCM_CABIN_DOOR                  = 0x27        // cabin_door_geo
export const MODEL_UNKNOWN_DOOR_28                 = 0x28        // referenced in special presets, undefined
export const MODEL_CASTLE_METAL_DOOR               = 0x29        // metal_door_geo
export const MODEL_CASTLE_GROUNDS_METAL_DOOR       = 0x29        // metal_door_geo
export const MODEL_UNKNOWN_DOOR_2A                 = 0x2A        // referenced in special presets, undefined
export const MODEL_UNKNOWN_DOOR_2B                 = 0x2B        // referenced in special presets, undefined
export const MODEL_WF_TOWER_TRAPEZOID_PLATORM      = 0x2C        // wf_geo_000AF8 - unused
export const MODEL_WF_TOWER_SQUARE_PLATORM         = 0x2D        // wf_geo_000B10
export const MODEL_WF_TOWER_SQUARE_PLATORM_UNUSED  = 0x2E        // wf_geo_000B38 - unused & duplicated
export const MODEL_WF_TOWER_SQUARE_PLATORM_ELEVATO = 0x2F        // wf_geo_000B60 - elevator platorm
export const MODEL_WF_GIANT_POLE                   = MODEL_LEVEL_GEOMETRY_0D        // wf_geo_000B60 - elevator platorm

export const MODEL_YELLOW_SPHERE                   = 0x55        // yellow_sphere_geo

// castle grounds
export const MODEL_CASTLE_GROUNDS_VCUTM_GRILL       =   0x36
export const MODEL_CASTLE_GROUNDS_FLAG              =   0x37
export const MODEL_CASTLE_GROUNDS_CANNON_GRILL      =   0x38